### ISSUE TITLE
Confusing labeling in Staking Dashboard

### ISSUE THREAD

**Issue by vepkenez** [threshold-network/token-dashboard#109]
on https://dashboard.test.threshold.network/staking using Ropsten:

When working with an existing stake the unstaked T balance in my wallet is appearing on a field labeled "Unstake Amount".  I believe the context is that I would be adding to the existing stake or "topping up" so the field label should reflect that.

<img width="567" alt="topUp" src="https://user-images.githubusercontent.com/188812/168143782-a17e8896-75d1-42c2-8f4a-10dfcdb5fc4c.png">

**Comment by r-czajkowski** [comment]
Hey 👋 ! Thanks for reporting an issue! Fixed here fefff9d7ad0ec0197ed79e07056c0c8ea6e1eaed.
