### ISSUE TITLE
Add Tally Ho as a wallet connection option 

### ISSUE THREAD

**Issue by Naxsun** [threshold-network/token-dashboard#115]
Similar to the Keep Dashboard add Tally Ho as a wallet connection option.

If helpful I can ask a community developer to submit a PR.

**Comment by pdyraga** [comment]
Bumping this up! We've just had a staker using Tally Ho wallet and they were not able to see their stake.

@r-czajkowski can we see how complicated this is? Maybe it's just a couple of hours of work given we have the code from the Keep dashboard. If it is more complicated, then we could probably use some help from the community.
