### ISSUE TITLE
Possible Alchemy Endpoint Configuration Issue

### ISSUE THREAD

**Issue by james-a-morris** [threshold-network/token-dashboard#125]
I wasn't sure where to place the question as it's not related to any one specific repository.  The issue I found has to do with the configuration of your production Alchemy endpoints on https://dashboard.threshold.network/. From some of the tests I ran, it seems that the endpoints do not have whitelisting applied to them.

I wanted to bring this up as those public endpoints could easily be taken to be used on a different website at Threshold's expense. And, if the API requests exceed Threshold's monthly quota, it could mean a denial of service (API endpoints returning failed responses) or a surcharge in additional fees.

#### A successful call of the Alchemy Endpoint being used on a different host outside of the prod/preview environment (dashboard.threshold.network and preview.dashboard.threshold.network)

![image](https://user-images.githubusercontent.com/96435344/173573696-1f24b105-778d-41a7-917f-dce81c693ffd.png)

#### A failed call of an Infura Endpoint (similar api interface | endpoint now disabled) being used on a different host outside of the prod/preview environment (dashboard.threshold.network and preview.dashboard.threshold.network) with whitelisting set

![image](https://user-images.githubusercontent.com/96435344/173574129-dbaae685-0118-4073-ad32-5d99e5147cdf.png)

**Comment by pdyraga** [comment]
Thanks for reporting it @james-a-morris. Proper rules have been applied. Can you please check on your end if endpoints behave as expected now?

**Comment by james-a-morris** [comment]
> Thanks for reporting it @james-a-morris. Proper rules have been applied. Can you please check on your end if endpoints behave as expected now?

It's completely resolved on my tests. You all do great work :smiley:
