### ISSUE TITLE
Migrate preview and test dashboard deployment to use Görli

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#135]
Migrate https://dashboard.test.threshold.network/ and preview to use Görli contracts (CI included)

**Comment by michalinacienciala** [comment]
Done.
Previews use packages tagged `dapp-development-goerli` (see https://github.com/threshold-network/token-dashboard/pull/161), the https://dashboard.test.threshold.network/ dashboard is built using `goerli`-tagged packages.
