### ISSUE TITLE
Multi-App-Staking Components

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#144]
- [ ] Min/Mid/Max Selectors
![Image](https://user-images.githubusercontent.com/15269424/180004845-2f478a55-5600-479e-b82a-9adbd28c0832.png)

- [ ] MAS Staking Card
![Image](https://user-images.githubusercontent.com/15269424/180005202-1eb1986c-7f0d-48aa-a093-625c82815bd6.png)

- [ ] Stake details header
![Image](https://user-images.githubusercontent.com/15269424/180005465-fd12e9ca-bace-4f0e-9fc2-d0b1d04a9f8e.png)

- [ ] App auth card
![Image](https://user-images.githubusercontent.com/15269424/180005592-5c6b5f9e-a96f-426c-92b3-e87608c52676.png)

- [ ] App increase card
![Image](https://user-images.githubusercontent.com/15269424/180005810-f605738f-593a-474a-bce0-bdb08cae4fb3.png)

**Comment by pdyraga** [comment]
@georgeweiler Should we close this issue now?

**Comment by r-czajkowski** [comment]
Done in [`v1.3.0` milestone](https://github.com/threshold-network/token-dashboard/milestone/2?closed=1).
