### ISSUE TITLE
MAS Figma Design (Post Usability Testing)

### ISSUE THREAD

**Issue by liz-shinn** [threshold-network/token-dashboard#146]
Figma design changes for Multi App Staking (MAS), post usability study.

- [x] Swap the secondary navigation so that they start from How it Works
- [x] Add a CTA button into the card on How it Works that says "Start Staking" that links to the Staking page.
- [x] Add the word "App" next to all of the app labels (PRE App, TBTC App, Random Beacon App)
- [x] Change the name of Configure Stake button into "Configure Apps"
- [x] Change the name of "Set Up a Node" to "Docs" in the node status alert.
- [x] Change the header modal copy in the success screen of Deauth Initation to be "Initiation Started" and the success alert to read "Your deauthorization was initiated. Your 14 day cooldown period has started." 
- [x] Change the header copy of Deauth Conf modal to be "The cooldown period is complete. Confirm your deauthorization."
- [x] Remove the Deauthorization Timeline in the Deauthorization Confirmation modal (the second half of the deauth flow).
- [x] Change header text copy in Stake Tokens (Step 1) modal to be "Staking in Threshold requires running a node."
- [x] Add in "Application" overview to the Staking card that has the application status (authorized or not) and the percentage authorization
- [x] Updates to the staking card designs
- [x] Removing the min/mid/max component
- [x] Updates to breadcrumb navigation
- [x] Updates to the tertiary navigation on the stake expansion page

**Comment by liz-shinn** [comment]
@georgeweiler I'm tracking the status of these changes here. Hopefully this is a clear way for versioning from existing design to the new one.

**Comment by liz-shinn** [comment]
<img width="232" alt="Screen Shot 2022-08-07 at 10 01 07 PM" src="https://user-images.githubusercontent.com/57226633/183310297-449d47a1-05d7-4488-8ee2-c1627aa4d1bd.png">
<img width="230" alt="Screen Shot 2022-08-07 at 10 01 12 PM" src="https://user-images.githubusercontent.com/57226633/183310298-ab08b530-2358-47ce-b807-4b9478068178.png">
<img width="326" alt="Screen Shot 2022-08-07 at 10 36 52 PM" src="https://user-images.githubusercontent.com/57226633/183310299-6381554c-c220-41b8-b947-2474f0abfdeb.png">
<img width="369" alt="Screen Shot 2022-08-07 at 10 41 31 PM" src="https://user-images.githubusercontent.com/57226633/183310300-d6538279-57da-47f3-9a8f-ab57684f762e.png">
<img width="266" alt="Screen Shot 2022-08-07 at 10 41 40 PM" src="https://user-images.githubusercontent.com/57226633/183310301-a1caf89b-894c-46a5-9b25-45ca44bdc49b.png">
<img width="264" alt="Screen Shot 2022-08-07 at 10 42 29 PM" src="https://user-images.githubusercontent.com/57226633/183310302-cf310124-71e1-43cc-8d8e-87802dbf0742.png">

**Comment by sashatanase** [comment]
@georgeweiler we might transform the min/mid/max component into something else based on the findings we've got from the interviews.

**Comment by liz-shinn** [comment]
Revisions to the min/mid/max component: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=5087%3A278256


![Image](https://user-images.githubusercontent.com/57226633/184396106-bf173441-c029-4760-b59b-f3ec84cc45ff.png)

**Comment by liz-shinn** [comment]
Revisions to the staking card: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=5131%3A295846



![Image](https://user-images.githubusercontent.com/57226633/184396227-27afc7f4-089a-47ab-9005-0c1a5bb49160.png)

**Comment by liz-shinn** [comment]
Breadcrumb and tertiary navigation:

![Image](https://user-images.githubusercontent.com/57226633/184396473-cec11ef2-6da2-45de-94c2-3c39223f1ad4.png)
