### ISSUE TITLE
Divider line for subnavigation pills is wrong color on mobile

### ISSUE THREAD

**Issue by georgeweiler** [threshold-network/token-dashboard#238]
![Screen Shot 2022-10-03 at 11 26 53 AM](https://user-images.githubusercontent.com/15269424/193640751-520fd775-55d2-4233-af93-34321312a845.png)

**Comment by r-czajkowski** [comment]
Fixed in #211, see this commit 2edcbfa.

**Comment by r-czajkowski** [comment]
Fixed in #211, see this commit 2edcbfa.
