### ISSUE TITLE
Authorization Confirm modal needs some updates

### ISSUE THREAD

**Issue by georgeweiler** [threshold-network/token-dashboard#253]
- [ ] Cards are missing the word APP in their title. 
- [ ] Typo - Random Beacon is written linked together.
- [ ]  Denominator missing - next to the amount of T authorized the T denominator should be displayed.
- [ ] Missing “Step 2” in the modal header

![Screen Shot 2022-10-03 at 12 46 12 PM](https://user-images.githubusercontent.com/15269424/193654716-e3e5600b-0ff6-4366-9dbc-4e96617790ed.png)

**Comment by r-czajkowski** [comment]
Regarding:
>  Missing “Step 2” in the modal header

Let's fix this as part of the https://github.com/threshold-network/token-dashboard/issues/251.
