### ISSUE TITLE
Missing path when decreasing authorization

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#266]
There are two possible outcomes of requesting an authorization decrease:
- If there is no staking provider <> operator mapping, there is no chance the operator is registered in a sortition pool. Thus, the sortition pool status must be up to date for that operator. In this case, the authorization decrease request [can be activated right away](https://github.com/keep-network/keep-core/blob/4e940f02b8bebeafcae2727016e00ea70355a709/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L287-L295).
- If there is a staking provider <> operator mapping, there is a chance the operator is registered in a sortition pool. Thus, the sortition pool status may require updating. In this case, the authorization decrease request [should be activated](https://github.com/keep-network/keep-core/blob/4e940f02b8bebeafcae2727016e00ea70355a709/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L297-L304) by the client with a call to [`updateOperatorStatus`](https://github.com/keep-network/keep-core/blob/4e940f02b8bebeafcae2727016e00ea70355a709/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L510).

There are two problems with the second case:
- One could set up staking provider <> operator mapping but could never set up a client.
- The operator who is not a beta operator could not join the pool. If they are deauthorizing to 0, from the sortition pool's perspective, their status is up to date (see [`RandomBeacon.isOperatorUpToDate`](https://github.com/keep-network/keep-core/blob/4e940f02b8bebeafcae2727016e00ea70355a709/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L551) and [`WalletRegistry.isOperatorUpToDate`](https://github.com/keep-network/keep-core/blob/4049dc0153c33c3c4cbb2e9a1808581bf76144fb/solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol#L554)). The client will not attempt to update the pool if the status is up to date.

The problem with a beta operator could be theoretically solved in the client by adding an additional path for updating the status. However, it is not possible to solve the first problem in the client.

I propose to solve these two problems in the dashboard in the following way: When the authorization decrease is requested, we check if there is a staking provider <> operator mapping. If such mapping exists, we check if the operator is in the pool. If not, we execute a call to `RandomBeacon.updateOperatorStatus` / `WalletRegistry.updateOperatorStatus`. When releasing a fix, we should also check if someone is in a problematic situation right now by looking at the events emitted by contracts. If so, we should call the `updateOperatorStatus` for them.

**Comment by r-czajkowski** [comment]
Released in v1.3.4.
