### ISSUE TITLE
Create wrapper for tbtc-v2.ts lib in threshold-ts lib

### ISSUE THREAD

**Issue by michalsmiarowski** [threshold-network/token-dashboard#310]
We should have a way to test out the tbtc-v2 functionalities with AND without a need to use test bitcoin chain.

To achieve that we should create a wrapper for `tbtc-v2.ts` lib in our `threshold-ts` lib which will wrap all needed functionalities and either use a proper functionality from `tbtc-v2.ts` lib (if we have a connection to bitcoin client) or mock the values that specific functionality would return (if we won't have a connection to a bitcoin client).

**Comment by pdyraga** [comment]
@michalsmiarowski Can we close this issue now? I see the two PRs referring to it have been merged.

**Comment by michalsmiarowski** [comment]
The issue was resolved in #314
