### ISSUE TITLE
(COSMETIC) The `x` character in the generated deposit address displayed incorrectly (as 'times'/'multiply' char)

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#368]
I generated new deposit address and noticed that one of the characters (`x`) is displayed in a weird way, resembling symbol of multiplication.
The other `x` character in the address was displayed normally.
When copied to clipboard and pasted to a text editor, the address looks good:`tb1qtx0ytj3sv0v4runu67ndgz45m7m8xarsan6qd3x25qvlv7r4qsrqft7mdq`.

![image](https://user-images.githubusercontent.com/78352137/214901454-90b1d639-7da4-433a-8632-157531572531.png)

**Comment by michalsmiarowski** [comment]
Update on the bug:

I think this happens when we have two numbers between the `x` characters. If there is any letter next to `x` it displays normally.

#383 should fix that but this info may be helpful to test it out.
