### ISSUE TITLE
(MEDIUM) Deposit flow doesn't react to sent funds when there is an earlier pending deposit

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#369]
The deposit gets stuck in the `Checking if funds have been sent...` state even after the fund have been sent. This happens if there is an earlier deposit connected to the Ethereum wallet which is in the `PENDING` state. Once the earlier deposit changes state to `MINTED`, the newer deposit unblocks (although first dApp needs to be refreshed) and `I sent the BTC` button appears.

Steps:
1. Connect to dApp with a wallet
2. Go to `tBTC` and create & reveal deposit. Deposit gets listed in the `TX HISTORY` panel as `PENDING`.
3. Using the same Ethereum account, soon after deposit is revealed, use the ◀️ to go back and confirm that you want to generate a new deposit. Fill the `Recovery BTC Address` field (can be a new value) and progress further.
4. After you sent the BTC to the deposit address there's no change in the dApp. The dApp is stuck on `Checking if funds have been sent...`
5. Wait until first deposit gets minted
6. Now you can progress with the second deposit - `I sent the BTC` option gets activated.

Expected: We should be able to progress with the second deposit even if first is still `PENDING`.

**Comment by pdyraga** [comment]
Two questions:

1. What do you think about changing the copy from `Checking if funds have been sent...` to `Waiting for funds to be sent...`? 

    I think this is what is actually happening under the hood. Having the spinner next to `Checking ...`, as a user, I have a feeling there is something wrong with server connection that makes it problematic to check the state. cc @sashatanase 

2. How do we currently check if funds have been sent? Based on the issue description, deposits were generated to two different P2SH addresses so there should be no problem in distinguishing them @michalsmiarowski @r-czajkowski

**Comment by michalsmiarowski** [comment]
@michalinacienciala I flagged this task in https://github.com/threshold-network/token-dashboard/pull/377 but to be honest I'm not sure if it resolves the issue you mentioned. I dind't find time to test it properly. If you encounter this bug again during testing please let me know 😉

**Comment by michalinacienciala** [comment]
Ok, I'll keep an eye on it!

**Comment by michalinacienciala** [comment]
@michalsmiarowski, I wasn't able to reproduce it recently, maybe it got fixed in #377 after all. I'll close the issue and if we see it occur in the future, we can reopen.
