### ISSUE TITLE
(MEDIUM) Change of the labels on the `Initiate minting tBTC` pop-up and in `Step 4`

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#373]
1. What we call in dApp the `Bitcoin Miner Fee` isn't actually the Bitcoin Miner Fee, it's a fee for optimistic minting. Could we rename it to `Minting Fee`?

2. We present the `Minted Amount` on `Initiate minting tBTC` pop-up  and in `Step 4`. When we show that, no tBTC is minted yet, so I would prefer to change the labels to `Amount To Be Minted` (or something other not suggesting that the minting actually took place)...

@sashatanase, what do you think?

![image](https://user-images.githubusercontent.com/78352137/215045869-73537108-d3d4-4721-bf4c-22217d4228e4.png)

![image](https://user-images.githubusercontent.com/78352137/215045901-eb567d85-6d1c-4d79-a4c5-3c35b3155751.png)

**Comment by r-czajkowski** [comment]
Should't we display fees in `tBTC`? @pdyraga The system doesn't send any BTC to Bitcoin treasury address but sends fees in tBTC to treasury address.
