### ISSUE TITLE
(MAJOR) No deposits under 0.01 BTC are able to be minted

### ISSUE THREAD

**Issue by mhluongo** [threshold-network/token-dashboard#390]
The dust threshold enforced by the minting contracts isn't displayed in the app, allowing users to mistakenly send ~$230 at today's prices, leaving it stuck for up to 9 months.

We need to
* Inform users of the dust limit at deposit time
* Give them a human-readable error if they sent too little BTC, and let them know about the refund instructions.

Below is when I realized I'd sent too little BTC.

![Screenshot from 2023-01-27 22-20-50](https://user-images.githubusercontent.com/427505/215240114-53e2f007-f7c5-4cca-8698-5ddcd3727a0a.png)

**Comment by pdyraga** [comment]
What about this @mhluongo @sashatanase, is this enough? 

![image](https://user-images.githubusercontent.com/4712360/215274614-69f23e88-9107-456d-b17d-7cd9b31b72e8.png)

**Comment by sashatanase** [comment]
So for this, we have it handled in the design here https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7760%3A199526&t=KYjqvDq92FqwH61h-1 and here https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7793%3A204627&t=KYjqvDq92FqwH61h-1

Meaning we have this information in the How it works page and in Step 2 

![image](https://user-images.githubusercontent.com/40768736/215288812-6636c22f-d7d7-42b7-b1d7-1140ee86cda9.png)
![image](https://user-images.githubusercontent.com/40768736/215288832-c78fd798-76be-4d90-85a4-e997eaa2e83b.png)

**Comment by michalinacienciala** [comment]
@r-czajkowski, I checked this and I still can't see the new copy. Are you sure it got fixed in #406?

**Comment by michalinacienciala** [comment]
Sorry for confusion, I made a mistake. The changes are there.
