### ISSUE TITLE
(COSMETIC) Grammar improvements in "How it works" page

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#396]
I would consider saying: "The amount you sent is the amount minted as tBTC" or "The amount you sent is the amount that will be minted as tBTC". I think the current version is not grammatically correct.

![image](https://user-images.githubusercontent.com/4712360/215276929-b17ce474-11f8-4d33-84cc-ba2e7aeac370.png)

**Comment by sashatanase** [comment]
I changed the copy to 

**Send any amount larger than 0.01 BTC to this unique BTC Deposit Address. The amount you send will be minted as tBTC.**

Ran it through Grammarly, should be correct now. 

Changes are here 
![image](https://user-images.githubusercontent.com/40768736/215282457-487c87e6-bfaa-4137-9d90-21562b7d662b.png)
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7760%3A199526&t=J7YNlampzgFUTkUw-1

**Comment by r-czajkowski** [comment]
> I changed the copy to
> 
> **Send any amount larger than 0.01 BTC to this unique BTC Deposit Address. The amount you send will be minted as tBTC.**
> 
> Ran it through Grammarly, should be correct now.
> 
> Changes are here ![image](https://user-images.githubusercontent.com/40768736/215282457-487c87e6-bfaa-4137-9d90-21562b7d662b.png) https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7760%3A199526&t=J7YNlampzgFUTkUw-1

Now we are inconsistent with changes suggested here https://github.com/threshold-network/token-dashboard/issues/398

Can we agree on one version and use in both places? cc @sashatanase
