### ISSUE TITLE
(COSMETIC) Grammar improvements in Step 2

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#398]
Three potential grammar fixes we need to apply in Step 2:

- We should say "a uniquely generated address". I think the current version is not grammatically correct.
- I would consider saying: "The amount you sent is the amount minted as tBTC" or "The amount you sent is the amount that will be minted as tBTC". I think the current version is not grammatically correct.
- Let's add a dot at the end of the sentence.

![image](https://user-images.githubusercontent.com/4712360/215277370-62ee3267-738a-42c2-b270-c69690236a4d.png)

**Comment by sashatanase** [comment]
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7793%3A204627&t=J7YNlampzgFUTkUw-1

Changes

here
![image](https://user-images.githubusercontent.com/40768736/215282104-7466184f-3b29-49d4-bb23-f2078e420000.png)

Here
![image](https://user-images.githubusercontent.com/40768736/215282112-9525bcab-b16f-4e89-ad22-39a0b486151b.png)

here

![image](https://user-images.githubusercontent.com/40768736/215282128-5807f1b4-048d-4627-916e-bfde431df11b.png)

Dot added.
