### ISSUE TITLE
(MAJOR) The Success page of the minting flow appears only for a brief moment after mint approve

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#402]
Sometimes during the minting flow we can observe a situation where after the mint/reveal transaction gets approved we're moved to the Success page which almost immediately changes to Step 1.

This may be confusing to users as they may be not sure if their minting request was successfully submitted.

It's yet unclear what is the exact rule for this behavior.

My steps:
1. On 2023-01-27 I made a new deposit using `0xC31D206f48EC365bc786563dE7cFb67fDb7e74e4` ETH Account and `2MxEbdguhdo8za6vJ9KwUJUpgU8jDUNejp8` recovery address. The ETH account that I used wasn't before used by me to any tBTC minting. I also for the first time used Firefox browser to do the test (so there should be no cache from old mintings there). I was accessing my ETH wallet via WalletConnect which allowed me to use mobile MM app. **After creation of that deposit I saw the Success page for the whole time, it didn't disappear immediately.**
2. Later that day I initiated a new deposit (I think it was when the first deposit was still pending). I used same ETH and BTC recovery addresses, same method of wallet connection. If I remember correctly I haven't reload the tBTC website since doing the first deposit. After I send the funds to the generated deposit address I progressed to the `Step 3` of the flow, where I'm supposed to confirm deposit & mint. I stopped at that stage for a few hours (didn't make a deposit), leaving the dApp open in one of my browser's tabs.
3. After those few hours (on 2023-01-28) I went back to the dApp tab and finally Clicked on `Confirm deposit & mint`. I saw the `Initiate minting` modal, checked the fees and progressed further (clicking `Start minting`). After I clicked, I noticed the transaction waiting for confirmation in my MM app. In the dApp I saw this:
![image](https://user-images.githubusercontent.com/78352137/215285471-5e110e86-0929-48d2-8b51-2a89169ee7d4.png)
4. I confirmed the tx in MM app and saw this for a couple of seconds:
![image](https://user-images.githubusercontent.com/78352137/215285498-eebea9e3-5052-4824-9827-99921e7896f7.png)
5. **Then the Success page was shown for a very brief moment (~1s) and after that I got directed to the `Step 1` again**:
![image](https://user-images.githubusercontent.com/78352137/215285533-88550923-1ba6-41da-a9d3-63c997ce69a0.png)

**Comment by michalinacienciala** [comment]
Now it looks to me that the issue occurs every time a deposit is confirmed. I tried different browsers, fresh ETH accounts, incognito mode - each time couldn't see the Success page longer that for a split second...

**Comment by r-czajkowski** [comment]
Should be fixed in #409

**Comment by michalinacienciala** [comment]
> Should be fixed in #409

Yes, I verified it, works as expected! 🚀
