### ISSUE TITLE
(MAJOR) Don't allow the user to use eth address other than his own

### ISSUE THREAD

**Issue by michalsmiarowski** [threshold-network/token-dashboard#403]
The dApp allows user to create a deposit address using address other than his own. We shouldn't allow this because after user sends his funds to the deposit address he won't be able to reveal the deposit. It will throw an error `Wrong 32-byte script hash`.

We should add some kind of validation to the form that checks if given eth address is equal to the one that is connected.

**Comment by pdyraga** [comment]
![image](https://user-images.githubusercontent.com/4712360/215289281-b9b9a3ac-49df-460f-813f-33c667f0f1eb.png)

**Comment by sashatanase** [comment]
We should make the ETH Address Read-only, as @pdyraga suggested.
