### ISSUE TITLE
(MEDIUM) The `ETH Address` does not get updated when user switches between accounts

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#407]
When user switches between accounts, the `ETH Address` does not get updated:

Let's consider two accounts that I have in my MetaMask:

* `Acc1: 0xC31D206f48EC365bc786563dE7cFb67fDb7e74e4`
* `Acc2: 0x58C6A45AcFCc1fD0E5A103Cab2caE00b0B188EC5`

Steps:

1. I open a fresh tab in the browser and go to https://dashboard.test.threshold.network/tBTC
2. I make sure that in my MM plugin I have `Acc1` selected
3. I click `Connect Wallet` -> `MetaMask` -> `View Dashboard`. I can see correct `ETH address`
![image](https://user-images.githubusercontent.com/78352137/215292935-18a0e8fb-101e-4bbd-a1da-578fb49a129b.png)
4. I open MM plugin, click on `Connected` next to account name and then I choose `Switch to this account` under `Acc2`. I can still see ETH address of `Acc1`:
![image](https://user-images.githubusercontent.com/78352137/215293005-c4be72d9-3e5d-4e13-bb97-cfc7739e6575.png).
5. If I progress with further steps of the minting, I can still see the wrong ETH account.

**Comment by michalsmiarowski** [comment]
Thanks for reporting! #404 should fix that
