### ISSUE TITLE
(MEDIUM) tBTC terms modal makes it look like users are locking funds for 9 months

### ISSUE THREAD

**Issue by mhluongo** [threshold-network/token-dashboard#413]
Alternate copy I'd suggest:

```
Minting Duration

→ Mint tBTC in ~1 to 3 hours. 

Minimum Deposits

→ The minimum deposit at launch is 0.01 BTC. Depositing less can mean losing access to your funds. Learn more.

Withdrawing BTC

→ Withdrawals are disabled on chaosnet, and won't be enabled for 3 to 6 months. Learn more.
```

![Screenshot from 2023-01-30 11-33-10](https://user-images.githubusercontent.com/427505/215537574-6955a451-3465-48e3-89ad-bed78b17b086.png)

![Screenshot from 2023-01-30 11-35-10](https://user-images.githubusercontent.com/427505/215538034-69a59dae-6a49-45ed-8d17-e9481aa65967.png)

**Comment by sashatanase** [comment]
We do not use the term *Withdrawal* anywhere else in the dApp. Is this the common language for bridging back? Also, we do not mention anywhere the name *chaosnet*, and I do not think users coming to bridge will know that unless you want to popularize it. @mhluongo

**Comment by mhluongo** [comment]
> We do not use the term _Withdrawal_ anywhere else in the dApp. Is this the common language for bridging back? Also, we do not mention anywhere the name _chaosnet_, and I do not think users coming to bridge will know that unless you want to popularize it. @mhluongo

Great callout on both. We'll be talking about chaosnet quite a bit over the next few weeks, but we haven't got enough material around it yet.
