### ISSUE TITLE
(COSMETIC) Change copy about .JSON file - mention BTC Recovery Address.

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#416]
We have the following sentence in HIW:
![image](https://user-images.githubusercontent.com/78352137/215555461-ab253144-ff7b-4069-9f49-45875bf6dab0.png)

We should update the copy to also mention the BTC Recovery Address, which is now stored in the file as well (because of https://github.com/threshold-network/token-dashboard/pull/380).

@sashatanase will update Figma.

**Comment by michalinacienciala** [comment]
Similar change needs to be done in the `Recovery .JSON file` modal as well.

**Comment by sashatanase** [comment]
Layouts with copy changes 
![image](https://user-images.githubusercontent.com/40768736/215556956-2452f32a-502f-4d38-a09c-ab11eb5b3903.png)
![image](https://user-images.githubusercontent.com/40768736/215557020-eb225942-edc2-4d79-910c-97f27b91307c.png)


How it works page
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7761%3A200410&t=T8Oxbe1nCwcPamqy-1

JSON Modal 
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7760%3A199526&t=T8Oxbe1nCwcPamqy-1
