### ISSUE TITLE
Show links to all ETH and BTC transactions (3 total on success) 

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#430]
We should show links to all transactions made by the user during the deposit flow: Etherscan and Blockstream.info (or another BTC block explorer).

**Comment by sashatanase** [comment]
![Image](https://user-images.githubusercontent.com/40768736/217048489-9655ae3a-ccd1-4bb2-bb6f-2c4f0bd32525.png)

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7907%3A209216&t=59lNq8DAGZokZBhL-1

**Comment by sashatanase** [comment]
@pdyraga I have two txs on success; which one is the third?

**Comment by pdyraga** [comment]
There are three transactions:
- Bitcoin deposited (transaction on Bitcoin)
- Optimistic minting requested (transaction on Ethereum)
- Optimistic minting finalized (transaction on Ethereum)

**Comment by mhluongo** [comment]
Note that including all of these in a detailed mint view was my original intent. There was an interim idea because I was looking for a way to roll it out in pieces to deliver value to users sooner.

**Comment by r-czajkowski** [comment]
> Note that including all of these in a detailed mint view was my original intent. There was an interim idea because I was looking for a way to roll it out in pieces to deliver value to users sooner.

I see. So displaying links to these transactions:
- Bitcoin deposited (transaction on Bitcoin),
- Deposit revealed (transaction on Ethereum).
on the `Sucess` page is OK? Or do we want to display optimistic minting requested, optimistic minting finalized as well? I wonder how many users leave the app open for at least 3 hours and wait for finalization 🤔. I'm definitely not that kind of user 😆.

**Comment by mhluongo** [comment]
> I wonder how many users leave the app open for at least 3 hours and wait for finalization on the Success page 

I did, because I was afraid to lose my money 🤷 It's new tech, and people will be anxious using it with large amounts of money.

I'm fine with displaying all of them in the success page, or working on a mint details page first. As long as we're addressing the pressing user need of being able to see the system state, and we can make some sort of useful change this sprint.

**Comment by mhluongo** [comment]
It's also not clear to the user whether the dApp will successfully keep the state — another reason for people to leave it open. Shipping to a mint details page with a persistent URL is the end goal as it addresses all of this, just want to iterate to that.

**Comment by r-czajkowski** [comment]
So I'll add all links to the success page so we can ship useful change this sprint. And in next sprint we can start working on the detailed view of the deposit. I like the idea of persistent URL eg. `/tBTC/deposit/<deposit_key>` where we could display all details.

**Comment by r-czajkowski** [comment]
Addressed in #446
