### ISSUE TITLE
Improving human readability on BTC Recovery Addresses. 

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#436]
**CONTEXT**
BTC Recovery Addresses need to be P2PFKH or P2WPPKH - this is a clunky and technical explanation both in the error message and on the HIW page. 
![image](https://user-images.githubusercontent.com/40768736/216837471-fa15acb4-c596-44cb-b3d7-665a92704633.png)

**PROPOSED SOLUTION**
Because non-sophisticated users, which are the majority of users, need to learn what the two abbreviations mean, we need to translate them into human. A human-readable way for these abbreviations will require a dynamic soltution. @r-czajkowski let me know if this is too complex so I can simplify it.

**For TESTNET**

**Tooltip**
in the BTC Recovery Address, we will add the following text
` This address needs to start with the letter "t" `

**Error message**
`The BTC Recovery address has to start with the letter "t", meaning it isP2PFKH or P2WPPKH compliant. _Read more_ `

**For MAINNET**

**Tooltip**
in the BTC Recovery Address, we will add the following text
` This address needs to start with the letters "bc" `

**Error message**
`The BTC Recovery address has to start with the letters "bc", meaning it is P2PFKH or P2WPPKH compliant. _Read more_ `

**Comment by sashatanase** [comment]
![image](https://user-images.githubusercontent.com/40768736/216837756-54af86ad-9170-47c6-a16e-59898ef10904.png)
![image](https://user-images.githubusercontent.com/40768736/216837773-9d674c3f-6704-4981-b988-173c6b3612c4.png)
![image](https://user-images.githubusercontent.com/40768736/216837778-8318c09f-7133-422a-8a5e-15ff6218be5e.png)
![image](https://user-images.githubusercontent.com/40768736/216837784-9cc22e05-e9b5-4f1f-b1c3-63c5f3af42f0.png)

Figma File- https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7897%3A208217&t=FOPoLr5XJ4rJrUdr-1

**Comment by sashatanase** [comment]
In How it Works page 
![image](https://user-images.githubusercontent.com/40768736/216837997-3fc7b1de-9017-420f-bee8-acaff1d1a562.png)

Figma File - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7897%3A208982&t=FOPoLr5XJ4rJrUdr-1

**Comment by sashatanase** [comment]
Open to suggestions.

**Comment by pdyraga** [comment]
Was this issue implemented @r-czajkowski @michalsmiarowski ?

**Comment by sashatanase** [comment]
Updating the designs. I made some small changes and I will leave here the final designs.

**Comment by pdyraga** [comment]
Unassigning @sashatanase as it is now in the implementation phase in the hands of @r-czajkowski.
