### ISSUE TITLE
Skip step 1&2 and jump to step 3 in the process of minting tBTC

### ISSUE THREAD

**Issue by dimpar** [threshold-network/token-dashboard#447]
Due to a browser and wallet incompatibility or simply by rejecting a transaction by a user in step 3, it might happen that the local storage will be lost. The problem is that a user doesn't know how to skip steps 1&2  and go straight to step 3 to resume minting. One of the options is to recreate local storage and paste JSON with the following format:
```
{
    "<eth_address>":
    {
        "ethAddress": "<eth_address>",
        "blindingFactor": "<blinding_factor>",
        "btcRecoveryAddress": "<btc_recovery_address>",
        "walletPublicKeyHash": "<wallet_publick_key_hash>",
        "refundLocktime": "<lock_time>",
        "btcDepositAddress": "<generated_deposit_address>"
    }
}
```
but this is not a friendly user experience.
![image](https://user-images.githubusercontent.com/3156420/218767870-07fb957c-1708-46c1-adb9-5315d656029b.png)

**Comment by sashatanase** [comment]
Watching this.
