### ISSUE TITLE
Show the minting progress

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#448]
I started from this here. 

I have this proposal for our lack of visibility of system status, and I took a stab at solving the issue.

Context: we received feedback that users need to learn what happens with their deposited tokens after they hit initialized minting. Our dApp doesn't provide any information about what is happening under the hood.

Proposal: Introduce a modal between Step 3 and Success that will showcase and sequence what is happening with the funds and the process under the hood.

Bear with me. I got down and dirty, so I might have breaks in alignments, padding, and other messy things.

https://github.com/threshold-network/token-dashboard/issues/430#issuecomment-1426045772

**Comment by sashatanase** [comment]
**Feedback received**

**Matt**

I like it! A couple of thoughts

* Generally, this feels like an extensive improvement / better exposure of the system status
* Instead of a modal, something that's more friendly to mints happening in parallel would be nice... especially if each mint gets its own dedicated, persistent URL. It's already unclear if it's safe to leave the dApp during a mint
* We'll be collapsing the "Bitcoin checkpoint" and "Minting initialized" steps over the next few releases to shave time off, so be ready for that. I don't think it's wrong though

Details on the last point - https://github.com/keep-network/optimistic-minting/issues/65

**Comment by sashatanase** [comment]
**Changes in version 2**

- I killed the timeline on the right-hand side since the user doesn't need to take any action anymore. they are just waiting for the dApp to do its magic. 
- used the new space to display the suite of transactions that happen during the minting process
- changed the timeline for the system status visually 
- added an animation that shows the metamorphosis from BTC to tBTC and killed the idea of a bridge
- changed the loading bar for the Bitcoin Network confirmations - there were too many linear elements and it was competing with the main timeline. 
- changed the success page. I removed some information from it - fees and stuff, and kept only the success message, the amount minted, and the transactions suite - BTC and ETH. 
- added on the success pool cards to entice the user into depositing.
- changed the Secondary nav title from _bridge_ to _dApp_

**Comment by sashatanase** [comment]
**Prototype**
https://www.figma.com/proto/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?page-id=7126%3A198919&node-id=8019%3A214048&viewport=-17975%2C-10463%2C0.6&scaling=min-zoom&starting-point-node-id=8006%3A212058

**Figma file**
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8006%3A212058&t=yhC2tjUk6hTH21qC-1

**Comment by sashatanase** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/40768736/219045693-fb57cf3d-b851-4515-96f0-bbeb7c5cf41d.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/40768736/219045769-dda460ca-c740-49f9-9706-1fbe2a670adf.png">
<img width="824" alt="image" src="https://user-images.githubusercontent.com/40768736/219045878-f6207c15-191f-49b7-9db1-88e9a983beda.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/40768736/219045991-8521277f-1b2b-4537-98b7-c6af33d8c402.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/40768736/219046088-110cf4b1-de7d-431c-932f-c31f9d20828d.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/40768736/219046172-829bb2e6-e779-4e66-93f7-34d176e7f907.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/40768736/219046227-63122c43-3caa-435f-b734-8cc2bd19dfac.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/40768736/219046322-1705e77b-d778-407d-ab9b-a4431766c95f.png">
<img width="825" alt="image" src="https://user-images.githubusercontent.com/40768736/219046401-24058f0b-1214-45e9-83ed-5c2f36da7d10.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/40768736/219046514-c96ca59c-c34a-4b96-baae-86145fc143a0.png">

**Comment by sashatanase** [comment]
@pdyraga I am not sure if this issue is in the right place. I wanted to add it in our Sprint Board but I am not able to.

**Comment by sashatanase** [comment]
@r-czajkowski let me know if there are any tech constraints that I may have missed.

**Comment by sashatanase** [comment]
Updated Designs

Bitcoin Checkpoint is a doughnut loader, and it will fill up in 6 steps.

![Image](https://user-images.githubusercontent.com/40768736/220361187-bf1fbbe0-7fdf-4aca-97d2-c7d47b813b3c.png)



![Image](https://user-images.githubusercontent.com/40768736/220361487-98deedfb-ff16-475c-acee-880577bf895b.png)



![Image](https://user-images.githubusercontent.com/40768736/220361526-ce19b14f-147f-439a-aa72-b4b5919c36b7.png)



![Image](https://user-images.githubusercontent.com/40768736/220361589-c4832d44-d14b-47d7-a747-895cb90fa3ed.png)

 Minter Check Point


![Image](https://user-images.githubusercontent.com/40768736/220362820-242f4bf1-dab1-49ce-aa65-d90ff92b451b.png)

The colour of the spinner will change so the user can perceive the progress and the change in the dApp state.



![Image](https://user-images.githubusercontent.com/40768736/220363048-ef9d35e6-3175-465d-b310-699fe662447a.png)

 On the right side, we are using that space to list the transactions that are happening and happened ( TX History)



![Image](https://user-images.githubusercontent.com/40768736/220363200-cb450d45-7cad-4934-b4f0-4bf4ce874575.png)


In the right corner, we provide them with some reading material tightly linked to the checkpoints + checkpoint explanations.


![Image](https://user-images.githubusercontent.com/40768736/220363672-875dd3f2-af6b-4bff-9ccf-da89180b7c75.png)






![Image](https://user-images.githubusercontent.com/40768736/220363559-2f4a7d8a-ddc9-452f-992d-289f975c437d.png)


![Image](https://user-images.githubusercontent.com/40768736/220363795-a08830e5-efd8-4064-b77d-924428d9b83e.png)



![Image](https://user-images.githubusercontent.com/40768736/220363849-371c00a8-86b6-47ce-a206-3df05ecde4a3.png)


Success page 



![Image](https://user-images.githubusercontent.com/40768736/220363918-28e97755-8e69-4fc8-880d-17245b86520e.png)

Figma Files here: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8099%3A273631&t=g2W4KHlv7VbgTc2D-1

@mhluongo please review thee checkpoint copy. I believe it needs a lot of polishing and is not the greatest. If you think I could tag someone else for copy please let me know.

**Comment by r-czajkowski** [comment]
I was thinking that we can use the same UI for a detailed view. The detailed view URL for the deposit could be `tTBC/deposit/<deposti_key>`. My understanding of the flow is:
- user revealed a deposit,
- after a successful transaction, the dapp redirects the user to `tTBC/deposit/<deposti_key>` where we will display all this stuff and display the correct status. A user can start a new mint, stay on the page or leave the dapp.

If a user closes the dapp we will start from the beginning(step 1), but we have a tx history table from which we can redirect the user to the `tBTC/deposit/<deposit_key>`. Eg. we could get rid of the `tx` column and add an internal link `View details`. On this page, we will display the proposed UI depending on the current status of the minting. cc @sashatanase

**Comment by sashatanase** [comment]
@mhluongo during my discussion today with @r-czajkowski  I learned that we plan to support more mints in parallel. This is a thing that I learned of, and I am wondering how we can accomplish this given the way the visibility of system status works now. 

Current flow:

- the user provides data -> generates P2KH unique deposit address
- sends funds to the deposit address
- reveals 
- minting in progress + visibility system status, which takes 3-4 hours

During the 3-4 hours, there is no way in the dApp to start a new mint unless they click on the Mint tab; otherwise, I do not see how they could do it. 

The only [New Mint] button on the success page appears after the tokens are successfully minted. 


- Do we want to support mints in parallel? 
- Is this something that brings value to our dApp?

I prefer to avoid supporting mints in parallel because it will overly complicate the experience and introduce confusion points.

**Comment by mhluongo** [comment]
It isn't high priority, which is why it hasn't landed on any sprints and we haven't spoken about it before! It's hit me personally as a user already, which is why I've mentioned it. But we have more pressing user needs first.

The persistent URL issue is related to minting in parallel, but it's important on its own so we can help people with support, etc.

**Comment by pdyraga** [comment]
Let's focus this issue only on the steps representing the progress.

Persistent links are covered here: https://github.com/threshold-network/token-dashboard/issues/456
The new success page if pool promo is covered here: https://github.com/threshold-network/token-dashboard/issues/455

I will update the issue title to make it clear.

**Comment by pdyraga** [comment]
Unassigning @sashatanase as it is now in the implementation phase in the hands of @r-czajkowski.
