### ISSUE TITLE
Links to recent deposits in dApp

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#458]
This issue is about displaying links to recent deposits in the dApp.

Website and dApp block explorer are handled in separate issues. See https://github.com/threshold-network/splash-page/issues/68 and https://github.com/threshold-network/token-dashboard/issues/469.

![image](https://user-images.githubusercontent.com/4712360/223138871-22c28e54-6996-4a72-9a1c-fa3ccae005d0.png)

![image](https://user-images.githubusercontent.com/4712360/223138903-30dfa83b-b0e5-485c-876a-366b5af362ad.png)

**Comment by sashatanase** [comment]
Okay, so this is a general history? I understand the idea, but I need to think of a place for it that would not confuse the users. Maybe we should have this in the Overview page.

**Comment by sashatanase** [comment]
"Across all wallets. The idea here is to show people that there were deposits recently.

If we have persistent deposit links, this is straightforward — we show some sort of table that includes links to recent deposits with a timestamp and amount. If we don’t have persistent deposit links, maybe we could just show EtherScan links of mints being finalized?"

We will use the same table in the dApp and the website, however since the website is Liz's area I want to tag her here as well for visibility. @liz-shinn 

What do we want to display in the table @pdyraga @mhluongo ?

| Wallet Address | Amount    | TX           |              Timestamp |
|----------------|-----------|--------------|-----------------------:|
| 0xAb4...7795   | 2.35 tBTC | 0x9ee...342a | 2023/02/21<br>14:59:33 |
| 0xAb4...7795   | 0.44 tBTC | 0x9ee...342a | 2023/02/21<br>12:32:33 |

**Comment by mhluongo** [comment]
This looks good to me! In the actual UI, the timestamp could be a date with a time on-hover or something... as long as they're ordered correctly and people can see recent activity, I think we're good.

**Comment by liz-shinn** [comment]
> Okay, so this is a general history? I understand the idea, but I need to think of a place for it that would not confuse the users. Maybe we should have this in the Overview page.

This will need to be very clear that it's not a history of the user's wallet activity.

On the website this will be easier to accomplish, considering it's a website and not related in actuality or in the user's mind to a connected wallet.

For the dapp, we would be fighting against an expectation that wallet data & activity is related to a connected wallet, like Sasha is pointing out here.

So this will need to be visually obvious that it's distinct for "Your' activity as well as in location within the dapp. Overview seems like the right spot to me.

**Comment by liz-shinn** [comment]
Further thoughts for within the dapp... The goal here is to show recent activity, right? In the context of the dapp, do we think that the user is really going to need/want all the info in that table?

How might we show recent activity of other users in an easily digestible way, that also doesn't appear to be historical transaction information of a user's wallet?

Perhaps a scrolling ticker or a marquee with recent deposits? Wdyt @sashatanase ?

On the website, the table seems like a great solution to me.

**Comment by mhluongo** [comment]
Great points. What I actually want on the business side is for the user to see this as part of their journey — for reassurance, similar to TVL in the staking dApp.

Doing it just in the website might cover that, depending on whether we send people directly to the dApp or not... but it's also a departure of the website from marketing collateral to acting as a mini "tBTC explorer".

Maybe what we need is a separate explorer :shrug:

**Comment by sashatanase** [comment]
> How might we show the recent activity of other users in an easily digestible way that also doesn't appear to be historical transaction information of a user's wallet?

We have a card that is called `My Activity` that shows the user's own action history. 

I'd show this all across tBTC TVL ONLY in the dashboard Overview page in the tBTC card  and the table only on the website as well. 

Otherwise, my only solution to have the cross dApp History is to display it below the dApp actionable areas.

**Comment by sashatanase** [comment]
> Further thoughts for within the dApp... The goal here is to show recent activity. In the context of the dApp, do we think that the user is really going to need/want all the info in that table?

That info in the table is the least we could display to make the information credible. 

The goal here is to reassure that the dApp is USED and PROVEN and that the users about to make a deposit are not taking a leap of faith; thus, we are showing the "ALIVENESS" and the usage of the dApp. 

In my opinion, we should show this in the critical places where the user needs to be converted and takes the decision and not where the user is actually taking action, so my proposal for the TVL cards  + dApp History tables should be on:

**- the Threshold website on the tBTC section** 
_- when we have huge numbers, we should also display this on the threshold homepage_
**- dashboard Overview page in the tBTC card**
**- in the tBTC warning/informative modal, we could also display the TVL** 

cc @mhluongo

**Comment by sashatanase** [comment]
We have an array of proposals for this in the other tickets. I will update this with the final solutions by the end of the sprint.

**Comment by sashatanase** [comment]
# FINAL DESIGNS 

Links to recent deposits will be displayed on the following pages:

1. Threshold.org tBTC section 
2. the Threshold dashboard Overview/homepage 
3. the tBTC dApp Empty State before the wallet connection 
4. tBTC Explorer ( page inside the dApp displaying stats + recent deposits)


##  Threshold.org tBTC section 



![Image](https://user-images.githubusercontent.com/40768736/222133610-d470ddac-7f57-4ceb-b5f4-7e4ec9bfa062.png)


![Image](https://user-images.githubusercontent.com/40768736/222135419-3b980e73-3cd6-4218-ab39-b903456a1ef0.png)

https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?node-id=2638%3A24802&t=OY3kc75ocO3XndmM-1

Figma File https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?node-id=2810%3A32124&t=OY3kc75ocO3XndmM-1

FIgma file for mobile - https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?node-id=2638%3A24802&t=OY3kc75ocO3XndmM-1

##  the Threshold dashboard Overview/homepage 

![Image](https://user-images.githubusercontent.com/40768736/222136014-6ab93a2d-11ba-4a10-bd55-0b064a0f05ea.png)


![Image](https://user-images.githubusercontent.com/40768736/222136166-58f84948-dbc6-4ca3-a845-c530a133a7ad.png)


![Image](https://user-images.githubusercontent.com/40768736/222136093-ac82665e-8429-48f0-9d4c-6dd9d16dda50.png)



![Image](https://user-images.githubusercontent.com/40768736/222136555-362c1c0a-2ac5-4d10-abc0-d3ca58073ea6.png)


Figma file here - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8221%3A278753&t=F2GkIBFvRzvHAH3c-1

## the tBTC dApp Empty State before the wallet connection 

![Image](https://user-images.githubusercontent.com/40768736/222137218-f52e3edf-175c-4d0f-9e94-20e6f371f8ce.png)

![Image](https://user-images.githubusercontent.com/40768736/222137423-4aaff34d-b8f9-4080-b663-efffcf381fe6.png)

![Image](https://user-images.githubusercontent.com/40768736/222137534-25ea6ff1-69b9-4b44-9f74-a4e5a8226fc5.png)

Just so you know, there are changes made to the Timeline Information hierarchy mentioned in older issues. Please do not forget about them 

Figma file here: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8221%3A302111&t=F2GkIBFvRzvHAH3c-1

## tBTC Explorer ( page inside the dApp displaying stats + recent deposits) - extension of the scope 

![Image](https://user-images.githubusercontent.com/40768736/222138721-89552d9e-8f6f-4f24-a24d-238147a60fda.png)

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8224%3A246360&t=F2GkIBFvRzvHAH3c-1


@mhluongo @pdyraga @r-czajkowski please review this.

**Comment by pdyraga** [comment]
Let's focus only on dApp links in this issue, without the tBTC explorer.

Website is covered here: https://github.com/threshold-network/splash-page/issues/68 and tBTC explorer is covered here: https://github.com/threshold-network/token-dashboard/issues/469. 

I'll update the PR description and title to make it clear.

**Comment by pdyraga** [comment]
Unassigning @sashatanase as the design part is done and it is queued for implementation.
