### ISSUE TITLE
tBTC minted over time 

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#459]
This should be both dApp and the website. We need designs and the code.

**Comment by sashatanase** [comment]
This is the overall TVL not the user's.

**Comment by sashatanase** [comment]
@liz-shinn this is important to be shown on the tBTC website as well.

**Comment by sashatanase** [comment]
We have an array of proposals for this in the other tickets. Will update this with the final solutions by the end of the sprint.

**Comment by sashatanase** [comment]
# FINAL DESIGNS 

Protocol TVL will be displayed on the following pages:

1. Threshold.org tBTC section 
2. Threshold.org homepage
3. the Threshold dashboard Overview/homepage 
4. the tBTC dApp Empty State before the wallet connection 
5. tBTC Explorer ( page inside the dApp displaying stats + recent deposits)

##  Threshold.org tBTC section 



![Image](https://user-images.githubusercontent.com/40768736/222139885-86527c37-e880-46fc-a63b-9a0a08d7a4f5.png)

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8224%3A241201&t=F2GkIBFvRzvHAH3c-1

## Threshold.org homepage


![Image](https://user-images.githubusercontent.com/40768736/222142431-0a0b8152-2e84-4f85-9022-e4693de870c0.png)

Figma file desktop https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?node-id=2810%3A32124&t=OY3kc75ocO3XndmM-1
Figma file mobile https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?node-id=2638%3A24802&t=OY3kc75ocO3XndmM-1

##  the Threshold dashboard Overview/homepage 

![Image](https://user-images.githubusercontent.com/40768736/222136014-6ab93a2d-11ba-4a10-bd55-0b064a0f05ea.png)


![Image](https://user-images.githubusercontent.com/40768736/222136166-58f84948-dbc6-4ca3-a845-c530a133a7ad.png)


![Image](https://user-images.githubusercontent.com/40768736/222136093-ac82665e-8429-48f0-9d4c-6dd9d16dda50.png)



![Image](https://user-images.githubusercontent.com/40768736/222136555-362c1c0a-2ac5-4d10-abc0-d3ca58073ea6.png)


Figma file here - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8221%3A278753&t=F2GkIBFvRzvHAH3c-1

## the tBTC dApp Empty State before the wallet connection 

![Image](https://user-images.githubusercontent.com/40768736/222137218-f52e3edf-175c-4d0f-9e94-20e6f371f8ce.png)

![Image](https://user-images.githubusercontent.com/40768736/222137423-4aaff34d-b8f9-4080-b663-efffcf381fe6.png)

![Image](https://user-images.githubusercontent.com/40768736/222137534-25ea6ff1-69b9-4b44-9f74-a4e5a8226fc5.png)

Just so you know, there are changes made to the Timeline Information hierarchy mentioned in older issues. Please do not forget about them 

Figma file here: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8221%3A302111&t=F2GkIBFvRzvHAH3c-1

## tBTC Explorer ( page inside the dApp displaying stats + recent deposits) - extension of the scope 

![Image](https://user-images.githubusercontent.com/40768736/222138721-89552d9e-8f6f-4f24-a24d-238147a60fda.png)

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8224%3A246360&t=F2GkIBFvRzvHAH3c-1


@mhluongo @pdyraga @r-czajkowski please review this.

**Comment by sashatanase** [comment]
@pdyraga , you might want to break this mammoth into more granular tasks.
