### ISSUE TITLE
Design/UX: tBTC dApp prototype testing

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/token-dashboard#460]
This task has sub-tasks

- [x] Updated clickable prototype
- [x] Participants recruitment ad
- [x] Participants' Screener
- [x] Recruiting
- [x]  Design the test
- [x] Interviews
- [x] Report

**Comment by sashatanase** [comment]
I put together this screener so we can get the most relevant participants.

**What I am interested in is:

Mandatory
- Bitcoins users
- RSK users
- Liquid Network

Optional
- Ethereum users
- Wrapped BTC owners

Nice to have
- Ordinal owners**

cc @mhluongo 

Screener here: https://threshold-research.typeform.com/usability-study

Please review it, and then I shall start to share it and recruit people.
