### ISSUE TITLE
tBTC System Status in the tBTC Overview Card

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#463]
We must display any pending mints and their status on this overview page. Please follow the information from the current Visibility of System Status designs we have. 

It should be on the dashboard Overview page. 

In this tBTC card we need to include

- dApp TVL
- user tBTC balance
- recent activity 
- system status for pending mints

**Comment by sashatanase** [comment]
Today more info has been added to our design brief, so I will coalesce all these tasks into one.

**Comment by liz-shinn** [comment]
Like Sasha notes above this is a duplicate. I will close this issue!
