### ISSUE TITLE
Exploration for tBTC dApp Stats

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#466]
# Social proofing + Trust and Confidence building in the critical moments of the user's decision-making process

Today more info has been added to our design brief, so I merged all these tasks. 

## Overview

**Context:** 

tBTC still needs to be established as a brand, and many potential users need social proofing, so they would decide whether or not to use the product. 

Social proofing can take a lot of forms, and the ones that are the most important in the crypto space are: associations with well-established protocols, high TVLs ( or just TVL), and an easy way to see the aliveness of the product. The typical user doesn't; they have the appetite to be a pioneer, so the more they see other users using the product, the more inclined they are to use it themselves. 

The behaviour observed from past research:

Most of the users who are interested in the product will check the TVL and will be more inclined to use a product if someone in their trusted inner circle uses the product (squad goals), someone who they admire and look up to like an influencer or figurehead associates with the product.

When trying a new product, most users will start with a small amount, wait for some months to check if the protocol passed the test of time, and then proceed to use a more significant amount of funds. 

**The needs turned into the design brief:**

- make the user feel less lonely and less of a pioneer
- build trust and confidence by displaying the protocol's stats
- display convincing data in critical decision moments to encourage conversion
- make sure we display the confidence-building data as the first thing the user sees to ensure anchoring and building a good first impression ( this is directly correlated with the marketing ads we run) 

## Proposed solutions

Taking everything mentioned into account, the solution proposed is a set of on-chain data (TVL + history table) displayed on

- the Overview page of the Threshold dashboard in the tBTC section
- the tBTC landing page from the threshold network website
- a separate tBTC dApp Overview (to support the routing from the Sponsored ads on various channels)

### **Flow 1 - User lands on the tBTC landing page**

The user is landing on the tBTC section of the Threshold Network website. They will be presented with Key stats about the bridge/protocol:
- TVL in USD
- No. of tBTC
- No. of mints
- No. tBTC Holder Addresses
- History table with - Minted amount. wallet address, timestamp

The information displayed can be changed and may support changes based on what the team decides is most representative. I chose to have the TVL in USD because it is the most prominent and flashiest number.

![image](https://user-images.githubusercontent.com/40768736/221286069-e91942cb-3bd0-4f4e-b855-7be33c6a5b2e.png)
Figma file - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8173%3A230571&t=RY8CfQ8Fl6SLE5hD-1

If they click `start minting`, they will be taken to the tBTC dApp on the bridge page.
![image](https://user-images.githubusercontent.com/40768736/221286296-a7b53024-a5a9-4333-996c-65db73be4b71.png)

We can either take them here on the minting side of the dApp, where the only information displayed is about the minting process. 
![image](https://user-images.githubusercontent.com/40768736/221287387-c158c665-154a-46bf-abc6-8d305d8fd038.png)
BTW @michalsmiarowski and @r-czajkowski, this is the correct Empty State for the tBTC bridge when the user is not connected.

Or we can take them to a Bridge Stats Page, where we mirror the information on the marketing website. 

![image](https://user-images.githubusercontent.com/40768736/221287572-e6bd37d0-eb55-40d2-8eb6-315aba52c2a8.png)
Figma file - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8177%3A230397&t=RY8CfQ8Fl6SLE5hD-1

### **Flow 2 - User lands on the Threshold Dashboard Overview from Google or other search engines**

![image](https://user-images.githubusercontent.com/40768736/221287937-bdfe2956-b4d2-43a1-aac8-610b8c04128a.png)
On the left side, we will showcase the TVL of the tBTC dApp and the latest three mints across the dApp. On the right side, we'll show information that concerns the user with the wallet connected.
Figma file -https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8172%3A229109&t=RY8CfQ8Fl6SLE5hD-1

If they're not connected, this is what they see.

![image](https://user-images.githubusercontent.com/40768736/221289763-5f495a62-5c0a-465c-baf4-9b4c64975d02.png)
Figma File  https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8173%3A233460&t=RY8CfQ8Fl6SLE5hD-1

When clicking on show more this is where they'll be taken 
![image](https://user-images.githubusercontent.com/40768736/221290162-ab567b4a-bb70-445f-857e-51961e7ed7c8.png)
Figma File https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8173%3A230018&t=RY8CfQ8Fl6SLE5hD-1

### **Flow 3 - User lands on the tBTC Bridge Stats Page  from the bridge instead of the Bridge dApp page*

![image](https://user-images.githubusercontent.com/40768736/221291825-296a82dd-774e-4fee-8018-7d65efe0f638.png)
![image](https://user-images.githubusercontent.com/40768736/221292421-73f0c5a4-1f58-476c-a944-85757a2e4fa7.png)
Figma file https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8177%3A230397&t=RY8CfQ8Fl6SLE5hD-1

@mhluongo , please review my proposal.

**Comment by sashatanase** [comment]
I wanted to check how other bridging or non-bridging products are presenting themselves to the world but this time I looked at it through the new lens Matt brought with the lack of data and stats that we show to the world and I checked:

**Polygon** 

They showcase their stats loud and clear on the homepage
https://polygon.technology/


![Image](https://user-images.githubusercontent.com/40768736/221527646-73ec5886-21b4-4fb9-b1cd-aa7db97c50b7.png)

However, they do not derail the user's attention in the dApp 


![Image](https://user-images.githubusercontent.com/40768736/221528286-634c1568-0eaf-43ad-bb61-7d28ea0b327a.png)

**Hop Exchange**

It does an abysmal job in terms of converting the user on its homepage but somehow they nailed it considering the number of users they have.

https://hop.exchange/

![Image](https://user-images.githubusercontent.com/40768736/221528825-be0845a2-9f82-49cc-9c07-a0ef8e3df57b.png)

the dApp 


![Image](https://user-images.githubusercontent.com/40768736/221528924-713e0dd3-0bc9-4e74-b2e4-1612a17c2af8.png)

**Wormhole**

Has their stats displayed but you have to dig for them. I guess they have this approach because they are already established on the market. 



![Image](https://user-images.githubusercontent.com/40768736/221530053-a9157a96-889d-400d-ad2f-3168a12fe731.png)



![Image](https://user-images.githubusercontent.com/40768736/221530602-fe4ffb98-6bd3-4c3f-a35d-a827a3b9e5d1.png)

https://wormhole.com/stats/

However, on their bridge, they do not display any stats


![Image](https://user-images.githubusercontent.com/40768736/221531027-0fcf5038-31ca-43f8-9521-d685026607d3.png)

But they link to the mother Wormhole website where you can find the stats if you are very motivated to find them. 

https://www.portalbridge.com/#/transfer


**Uniswap**

Right below the fold, Uniswap presents its stats to convince users. it doesn't matter if they are an established protocol they are still working to convince and convert newcomers.

https://uniswap.org/


![Image](https://user-images.githubusercontent.com/40768736/221532519-38b8f768-a6ca-4f04-9710-7b79034e25c8.png)

However, on their dApp, they keep it clean and do not add extra information to derail the user's attention. 


![Image](https://user-images.githubusercontent.com/40768736/221532849-210cf223-4593-4edd-be50-2d1ce5c70624.png)



So following my research on  other bridges' marketing websites and dApps through the lens brought by  Matt's feedback on the way we present ourselves concerning the lack of data on our Marketing website, I propose:

- bringing the Network stats to the Threshold. network homepage with an emphasis on tBTC.
- add the stats on the tBTC section page - focused only on tBTC
- Try to capture the TVL in some of the marketing comms
- lead from the ads to either the tBTC section of the threshold.network website or (if we decide to keep it) the tBTC dApp stats page. 

Since this is a proposal that concerns Marketing and Growth as well I'd like to hear Hagan's and Brian's opinions and of course Matt's @mhluongo

**Comment by liz-shinn** [comment]
Thanks for your research here! I reference these and did a graph of some of my versionings, but I think it's too small of a space. I opted instead to not include it in the one I shared on the GH ticket: https://github.com/threshold-network/token-dashboard/issues/462
<img width="906" alt="Screenshot 2023-02-27 at 8 09 45 PM" src="https://user-images.githubusercontent.com/57226633/221726191-c4d3cc64-71f2-4969-b59d-40958cb47819.png">

**Comment by liz-shinn** [comment]
Synced with @sashatanase and we're closing this in favor of using 1 single issue to track design iterations! This is research and exploration above.
