### ISSUE TITLE
tBTC Explore - Stats Page inside of the dApp

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#469]
Design 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/40768736/222143913-2c709b14-d2f5-4e2e-90e0-c5015372537e.png">
Figma File - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8224%3A246360&t=F2GkIBFvRzvHAH3c-1

**Comment by sashatanase** [comment]
@pdyraga I opened a separate issue for this.

**Comment by pdyraga** [comment]
Unassigning @sashatanase given the design part is over and it is queued for implementation now.

**Comment by pdyraga** [comment]
Can we close this issue now @r-czajkowski ?

**Comment by r-czajkowski** [comment]
> Can we close this issue now @r-czajkowski ?

Nope. We implemented tBTC stats on overview page see https://github.com/threshold-network/token-dashboard/issues/428 and https://github.com/threshold-network/token-dashboard/issues/458. As I remember the separate page for the tBTC explorer was a stretch goal for the last sprint. I'll take this task for the next sprint.
