### ISSUE TITLE
My Activity Card Changed Behavior

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#471]
As a result of my discussion with Rafal, and based on the latest feature of having persistent URLs, I have updated the formerly known `History` card into `My Activity `

This `My Activity` card has suffered a redesign and behaviour update. 

**Design** 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/40768736/222147154-bb78173a-c4a4-4a99-b394-55566ef70751.png">

**Behaviour Description** 
The dApp will open the Success page corresponding to the reveal TX whenever the user clicks on a row from this table. I suggest we open a new tab for each Row. 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/40768736/222147800-4501e6bf-09a2-441a-a6b7-493a05db5ee0.png">
 
Figma File https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8221%3A266240&t=F2GkIBFvRzvHAH3c-1

@r-czajkowski please let me know if it makes sense from the technical aspect of our dApp.

**Comment by pdyraga** [comment]
Unassigning @sashatanase as this is queued for implementation now.
