### ISSUE TITLE
Posthog Tracking MVP

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#479]
# Posthog Tracking MVP

Currently, Posthog is tracking some user paths; however, how the data is displayed needs to be more revealing.

![image](https://user-images.githubusercontent.com/40768736/225317884-1286c37c-c394-4eb0-b482-93a4fb934dd9.png)

As you can see, we do not know what is `First Page`, `Second Page`, etc.

## What we need to track:

1. User cohorts funnelled from the marketing website to the tBTC dApp.
2. User cohorts on the tBTC dApp.

## 1. User cohorts funnelled from the marketing website to the tBTC dApp.

We must track how many users click on `Start Minting` from the threshold.network homepage out of the Unique Visting Users.

![image](https://user-images.githubusercontent.com/40768736/225318994-682f8f3e-c404-46c8-a8ba-430bf1a23493.png)

I am also interested in how many users click on `Learn more` button from the tBTC bridge homepage section 
![image](https://user-images.githubusercontent.com/40768736/225323906-2ed35238-f6fb-4e1c-b481-ab1f7728499b.png)
and how many out of these users click on `Mint tBTC` 
![image](https://user-images.githubusercontent.com/40768736/225324350-541fa6da-005b-4277-832e-14aac38b495c.png)

Of all these users who were brought on the tBTC dashboard page, I'd like to know how many users click on ` I agree, let's do it!` and how many users bounce off here.

![image](https://user-images.githubusercontent.com/40768736/225319804-b26caffe-33b2-498d-9999-a5511dd6171f.png)
We also want to track their next moves if they click `How it Works` after arriving on the tBTC first screen. We won't consider this a bounce. 

We won't consider this a bounce if they click on the `Bridge Contract`. However, if they close the tab, it will be regarded as a bounce. I am not interested in how much time they spend on this page. (for now) Clicking on `Github` or `Discord` without closing the tab will not be a bounce.

![image](https://user-images.githubusercontent.com/40768736/225321648-bd0da2e9-a76c-491d-a5ab-71f6fbb89625.png)

If they connect their wallets, I am also interested in how many users are connecting their wallets on this page. Not connecting their wallets will be considered a bounce. 

![image](https://user-images.githubusercontent.com/40768736/225323187-5b5b99ec-d3d8-4508-bf47-5d5faaaac8f4.png)

## 2. User cohorts on the tBTC dApp.

Of all these users who were brought on the tBTC dashboard page, I'd like to know how many users click on ` I agree, let's do it!` and how many users bounce off here.

![image](https://user-images.githubusercontent.com/40768736/225319804-b26caffe-33b2-498d-9999-a5511dd6171f.png)
We also want to track their next moves if they click `How it Works` after arriving on the tBTC first screen. We won't consider this a bounce. 

We won't consider this a bounce if they click on the `Bridge Contract`. However, if they close the tab, it will be regarded as a bounce. I am not interested in how much time they spend on this page. (for now) Clicking on `Github` or `Discord` without closing the tab will not be considered a bounce

![image](https://user-images.githubusercontent.com/40768736/225321648-bd0da2e9-a76c-491d-a5ab-71f6fbb89625.png)

If they connect their wallets, I am also interested in how many users are connecting their wallets on this page. Not connecting their wallets will be considered a bounce. 

![image](https://user-images.githubusercontent.com/40768736/225323187-5b5b99ec-d3d8-4508-bf47-5d5faaaac8f4.png)

BOUNCE: Not generating a deposit address 
![image](https://user-images.githubusercontent.com/40768736/225329204-76cf6b1f-1393-4ec0-ae76-6cdeaf00aa24.png)

BOUNCE: if they close the tab here on the JSON file modal
![image](https://user-images.githubusercontent.com/40768736/225328442-b0d7059d-0b61-4129-8a6c-861a252f225a.png)

REAL BOUNCE: Not sending the BTC funds
![image](https://user-images.githubusercontent.com/40768736/225329542-c45138fa-6770-47cd-8cb2-085a9dd2aa73.png)

BOUNCE & BIG ISSUE: Not revealing 

SUCCESS: Revealing 

CRAZY SUCCESS: if the same user mints again.

**Comment by pdyraga** [comment]
@michalsmiarowski Can we close this issue now?
