### ISSUE TITLE
Threshold Website Banner CTA

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#487]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/40768736/230080668-eef97ad1-ce66-452a-acb1-7d520f6150e6.png">

Change the copy and link in the ribbon banner -  I need the link to the launch campaign.

**Comment by r-czajkowski** [comment]
@sashatanase can we close this issue? I believe we addressed this here https://github.com/threshold-network/splash-page/pull/71.
