### ISSUE TITLE
Keep Dashboard Legacy Warning

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#488]
Add a Banner take-over warning explaining that the Keep dashboard is a legacy dashboard and doesn't support any other feature but:
-  unstaking
- grants withdrawal
- coverage pools withdrawal 

Re-direct users towards the threshold dashboard or stay on the Keep dashboard. 

Banner take-over behaviour:

The Banner will be shown once per IP connection; when the modal is dismissed, it will not be shown again. However, we will have a permanent ribbon banner explaining that the keep dashboard is a legacy dashboard.

@pdyraga  could you please confirm the features we still support for the keep legacy dashboard?

**Comment by sashatanase** [comment]
I have some questions for you about the Keep dashboard and its applications.

How long are we planning to keep the Keep Cov Pools alive? I see that we still allow people to deposit. 
- I believe we do not allow people to delegate their stakes, and I believe we only allow them to undelegate. For how long will we support the keep stakes undelegation?
- We still show two pools as working... the Saddle pool and mStable. Should we give them the same treatment as the obsolete ones?
- Is the tBTC token upgrade portal still working? How much does tBTC v1 still need to be upgraded?
- How many stakers do we still need to roll into Threshold?
- When is the token grants programme going to end?

If there are many features we aren't supporting any longer, I suggest removing them from the dashboard. 

What do you think? cc @pdyraga @mhluongo

**Comment by sashatanase** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/40768736/230109802-42c054be-48a4-4152-9485-e217e931b003.png">
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40768736/230109897-09fa9d4d-a88e-41f4-bca9-5862db09e1f4.png">
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/40768736/230110052-f423185d-57ca-44d4-83fb-c5661cd0a8ce.png">

Figma file - https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=14404%3A107378&t=DCl8kdUVU8bjWDU7-1

**Comment by sashatanase** [comment]
Answers from Piotr


- for how long are we planning to keep alive the Keep Cov Pools? I see that we still allow people to deposit. 

Ideally, they should be only able to redeem. There is no reason to deposit into the pool now. There are no rewards.

- I believe we do not allow people to delegate their stakes, and I believe we only allow them to undelegate. For how long will we support the keep stakes undelegation?

We allow to delegate and undelegate. We must allow it as long as there are KEEP grantees out there. I think this will take years unless we plan with the DAO how to workaround it. It's not on a roadmap right now and I don't think it has a high priority.

- We still show two pools as working... the Saddle pool and mStable. Should we give them the same treatment as the ones that are obsolete?

I do not think they earn any rewards.

- Is the tBTC token upgrade portal still working? How much tBTC v1 still needs to be upgraded?

0, we should remove it. It is no longer working.

- How many stakers do we still need to roll into Threshold?

No data. All KEEP holders can wrap in Threshold dashboard though.

- When is the token grants programme going to end?

We are not creating any new KEEP grants. If there are people receiving tokens we do it in some other way. There are people who received grants and are staking from that grant though. Unstaking from a grant needs to be supported for them.

**Comment by sashatanase** [comment]
Updated designs based on these answers



![Image](https://user-images.githubusercontent.com/40768736/230121692-af13c1de-b2ae-4b2f-9a5d-9f661d408b20.png)



![Image](https://user-images.githubusercontent.com/40768736/230121791-ae28afec-e7a7-46ed-91b3-cebd89411aae.png)

**Comment by sashatanase** [comment]
Request for Review @mhluongo

**Comment by sashatanase** [comment]
Discussions sparked by the legacy Keep dashboard and what changes it should suffer in the future. 


- for how long are we planning to keep alive the Keep Cov Pools? I see that we still allow people to deposit. 

Ideally, they should be only able to redeem. There is no reason to deposit into the pool now. There are no rewards.

- I believe we do not allow people to delegate their stakes, and I believe we only allow them to undelegate. For how long will we support the keep stakes undelegation?

We allow to delegate and undelegate. We must allow it as long as there are KEEP grantees out there. I think this will take years unless we plan with the DAO how to workaround it. It's not on a roadmap right now and I don't think it has a high priority.

- We still show two pools as working... the Saddle pool and mStable. Should we give them the same treatment as the ones that are obsolete?

I do not think they earn any rewards.

- Is the tBTC token upgrade portal still working? How much tBTC v1 still needs to be upgraded?

0, we should remove it. It is no longer working.

- How many stakers do we still need to roll into Threshold?

No data. All KEEP holders can wrap in Threshold dashboard though.

- When is the token grants programme going to end?

We are not creating any new KEEP grants. If there are people receiving tokens we do it in some other way. There are people who received grants and are staking from that grant though. Unstaking from a grant needs to be supported for them.

### Low-hanging fruit changes:

- we remove the pools section
- remove the possibility to deposit in the coverage pools since there are no longer rewards

**Comment by sashatanase** [comment]
@pdyraga This is what I would like you to present briefly for the demo on Monday. I am OOO.

**Comment by erdogan** [comment]
@lukasz-zimnoch - tagging you here since this was assigned to @pdyraga

**Comment by lukasz-zimnoch** [comment]
@pdyraga what is the current status here?

**Comment by pdyraga** [comment]
We have to publish a new Docker image version and deploy it. Just the "ship it" part.

**Comment by lukasz-zimnoch** [comment]
v1.20.0 deployed
