### ISSUE TITLE
Duplicate "Connect wallet" prompt

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#500]
There are two "connect wallet" prompts - we should hide one of these, prob the orange one. 

![image](https://user-images.githubusercontent.com/14485/234969891-1442f8c3-b271-4c65-9dd7-079654cca26f.png)

**Comment by erdogan** [comment]
@michalsmiarowski @r-czajkowski still seeing double prompts in current dashboard - was this not fixed? 
![image](https://github.com/threshold-network/token-dashboard/assets/14485/a4a292d6-cf7d-4a56-a962-792bfdb25f7f)

**Comment by r-czajkowski** [comment]
> @michalsmiarowski @r-czajkowski still seeing double prompts in current dashboard - was this not fixed? ![image](https://user-images.githubusercontent.com/14485/242898245-a4a292d6-cf7d-4a56-a962-792bfdb25f7f.png)

We haven't released a new version yet. Here is a testnet dashboard https://dashboard.test.threshold.network/overview/network where you can see the current `main` branch.

**Comment by erdogan** [comment]
Got it, thank you!
