### ISSUE TITLE
Text / copy edits for the minting dapp

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#503]
(Combining all edits into one issue to reduce clutter in the backlog)

- [x] Remove "Take note" text from the top left of the modal
- [x] Replace the fine print with "By clicking the button below, you acknowledge and accept the above terms"

![image](https://user-images.githubusercontent.com/14485/234988801-9f1f4297-6526-4400-84e9-e2aebf289cea.png)

- [x] Change the modal text with the below
> Recovery Receipt 
> ### Download for your records
> Recovery Receipt is important in the rare case of fund recovery. Keep it until you have successfully initiated minting. It is unique for each deposit and contains your BTC refund address, wallet public key, refund public key, and refund lock time of your deposit. 

![image](https://user-images.githubusercontent.com/14485/234984320-08742ce9-0f1a-4fd8-a3e7-260db5551f11.png)

- [x] Remove yellow alert box and text
- [x] Change button label to "Initiate Mint" 

![image](https://user-images.githubusercontent.com/14485/234980625-845a0327-87f9-4aa0-b517-ba365ba6ab93.png)

- [x] Replace the subtext ("Minting tBTC is a process ...") with “Minting tBTC requires a single transaction on Ethereum network and takes approximately 3 hours”
- [x] Replace "Read more about the bridge contract" with "View bridge contract on [Etherscan](url)"

![image](https://user-images.githubusercontent.com/14485/234987582-0295ad87-fac3-482a-874c-4b09d017d50c.png)

- [ ] Remove the large orange spinner
- [ ] Before the "Minting Initialized" title, add a neutral info-alert box with the following text
> ### It is safe to close this window
> Minting will continue as a background process and will not be interrupted. 

![image](https://user-images.githubusercontent.com/14485/234985442-8b0148f8-40ca-4af2-aad4-c5086ca64e7f.png)

**Comment by sashatanase** [comment]
>  Remove the large orange spinner

We talked about this and it's not going to make it.
