### ISSUE TITLE
Update staking provider list

### ISSUE THREAD

**Issue by mswilkison** [threshold-network/token-dashboard#527]
This list of staking providers is outdated. 

Bison Trails and Figment do not support T staking and should be removed. I'm unsure if Low Fee Validation supports T or not?

InfStones is not PRE only afaik so they can be moved to the other column. And let's remove Ankr as well, which means we don't need separate columns at all.

<img width="992" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/2382226/4caea112-8bdd-42d3-b0f0-68ba96053032">

**Comment by r-czajkowski** [comment]
Updated in #596
