### ISSUE TITLE
Deploy L2 canonical token and gateway to Base

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#535]

**Comment by pdyraga** [comment]
This issue should land in `keep-network/tbtc-v2`. Unfortunately there is no way to move issues cross-org. Can we close this one and open a new one?

**Comment by erdogan** [comment]
Closing this issue as **duplicate**,  recreating in `keep-network/tbtc-v2`
https://github.com/keep-network/tbtc-v2/issues/637
