### ISSUE TITLE
[Threshold Dashboard STAKING] Banner to inform the users they need to run a node. 

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#567]
**Context:** Even though in the Threshold Staking flow, the users are informed that they need to run a node, a lot of the users tend to braise over the information and not record it, thus resulting in a lot of people ending up lacking their funds for 45 days. The information was corroborated by customer support. 

Nowadays, STAKING in web3 has two connotations simultaneously; the first is about securing a network and running a node in PoS networks, and the other means providing liquidity in a liquidity pool from a DeFi protocol.

**Proposed Solution:** Safe route

Display a modal takeover right after the users click 'New Stake.' 
![image](https://github.com/threshold-network/token-dashboard/assets/40768736/487c2206-c846-4e4b-943f-cfd9311232e8)

This takeover should contain the following:

- a body copy letting users know that the Threshold Staking Process requires running a node and that the staking process is not a passive one
- a link to the Documentation - https://docs.threshold.network/staking-and-running-a-node/running-a-node
- a visual cue that helps users understand that this node is a computer or a server 
- Presents two options for running a node:
       - 1. Self-operated nodes - https://docs.threshold.network/staking-and-running-a-node/running-a-node/self-managed
       - 2. With the help of Staking Providers - https://docs.threshold.network/staking-and-running-a-node/running-a-node/staking-providers
       
It should also contain an agreement text.

"By clicking [insert_CTA_verb], I acknowledge I am aware of the requirements for the Threshold Staking."

[ I consent/I agree/Okay, let's go!]

The designer should decide the behaviour of this takeover

Figma file for the staking process and designs [here](https://www.figma.com/file/58VmYkAMjsEkEsryPBM0Rb/Archived-Threshold-Dapp-Designs?type=design&node-id=6101%3A371430&mode=design&t=yUYrE9j3TIbgN7PY-1)

```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/632
```

**Comment by SorinQ** [comment]
### Proposed solution

**Staking Timeline Pop-up**  
1. Update the text of the first pop-up in the staking flow. 
2. Add a new warning notification at the bottom. 
<img width="1278" alt="Screenshot 2023-08-01 at 15 05 43" src="https://github.com/threshold-network/token-dashboard/assets/37292909/298e57ad-d9e5-4a99-9056-40da519ddc1f">


**Stake Tokens (Step 1)**  
1. Add a new area at the bottom that requires user acceptance before proceeding further. 
2. The Read more link button should open in a new tab the following page: 
https://docs.threshold.network/staking-and-running-a-node/running-a-node 

<img width="1702" alt="Screenshot 2023-08-01 at 15 05 50" src="https://github.com/threshold-network/token-dashboard/assets/37292909/a1ca3856-d3dd-49e4-b217-efa5a27fa0d3">


**Component behavior:**  
- The button remains in a disabled state until the user ticks the checkbox in the new area.  
- As soon as the user checks the box, the button becomes active and allows the user to proceed further.


Figma link [here](https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Exploration?type=design&node-id=168-9549&mode=design&t=kttlQ1jQ797phOnL-4)



  
**Out of scope**
> A visual cue that helps users understand that this node is a computer or a server 
> Presents two options for running a node: 
> - 1. Self-operated nodes - https://docs.threshold.network/staking-and-running-a-node/running-a-node/self-managed 
> - 2. With the help of Staking Providers - https://docs.threshold.network/staking-and-running-a-node/running-a-node/staking-providers

**Comment by kpyszkowski** [comment]
@SorinQ please let me know if my changes meet your expectations https://preview.dashboard.test.threshold.network/feature/staking-running-node-notice
