### ISSUE TITLE
Dashboard typo: "unmit"

### ISSUE THREAD

**Issue by ThresholdLady** [threshold-network/token-dashboard#579]
![image](https://github.com/threshold-network/token-dashboard/assets/114190944/c8348027-e7d4-4eb8-9382-f54c607004bf)

**Comment by ThresholdLady** [comment]
@sashatanase are you able to take a look at this?

**Comment by ThresholdLady** [comment]
@nkuba can you take a look at this?

**Comment by mhluongo** [comment]
Pull request opened, should be resolved shortly.
