### ISSUE TITLE
TBTC Dash Still states redemptions are "under construction" 

### ISSUE THREAD

**Issue by nico186** [threshold-network/token-dashboard#584]
It was mentioned in the Threshold Discord (see link below) that: https://dashboard.threshold.network/tBTC/how-it-works still states redemptions/unminting are listed as "Under Construction for 3-6 months". For visibility I wanted to open an issue here.

Link to Discord post: https://discord.com/channels/866378471868727316/866378471868727319/1133802842805768304

**Comment by r-czajkowski** [comment]
Fixed in #582
