### ISSUE TITLE
Not user-friendly message in staking form when user does not have any T

### ISSUE THREAD

**Issue by michalsmiarowski** [threshold-network/token-dashboard#634]
When user does not have any T in his wallet we still display him that the minimal amount to stake is 40K:

<img width="520" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/e4d15745-0e94-4863-b469-e4a016e0c39a">

When we put the correct value there it shows that the value should be less than or equal to 0:

<img width="520" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/171784ff-b6e5-4e3f-9a20-002a191cd583">

We should display a proper error when user does not have any T (for example "You don't have that many T tokens in your wallet." cc @sashatanase @SorinQ).

We should also check what happens when users have some T but not enough to do stake (> 0 and < 40,000 T).
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/643
```

**Comment by kpyszkowski** [comment]
@michalsmiarowski What is the minimum stake amount? Now it allows me to stake 0.0T. Is is desirable behavior?
Uploading Screen Recording 2023-10-04 at 13.42.25.mov…

**Comment by michalsmiarowski** [comment]
It looks like for Goerli the minimum value is 0. On Mainnet it's 40k T. From what I see we also have a 40k minimum amount set in `goerli-dapp-development` packages. You can install them locally by running:

```
yarn upgrade @keep-network/ecdsa@dapp-development-goerli \
  @keep-network/random-beacon@dapp-development-goerli \
  @keep-network/tbtc-v2@dapp-development-goerli \
  @threshold-network/solidity-contracts@dapp-development-goerli
```

The error - "You don't have that many T tokens in your wallet" - should pop out if the value in the input exceeds tha value in the user's wallet. If this condition is met, then we should check if value in input is greater or equal to minimal value (which is 40k T). If not the we display the error that is implemented right now ("The value should be greater than or equal to <minimal_value>")
