### ISSUE TITLE
tBTC TVL value is too big in tBTC Explorer page

### ISSUE THREAD

**Issue by michalsmiarowski** [threshold-network/token-dashboard#635]
The tBTC TVL value is too big on mobile. We should make it smaller based on the resolution. See https://chakra-ui.com/docs/styled-system/responsive-styles

<img src="https://github.com/threshold-network/token-dashboard/assets/40306834/a681e410-af10-4df8-87c9-7703cfa7aee8"  height="500">

Phone used: iPhone 13 mini
Browser: Google Chrome

```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/638
```

**Comment by jMyles** [comment]
https://getyarn.io/yarn-clip/f413c399-aa97-4021-8f76-0ad8b07121e4
