### ISSUE TITLE
Link to Staking documentation for all apps

### ISSUE THREAD

**Issue by theref** [threshold-network/token-dashboard#673]
![image](https://github.com/threshold-network/token-dashboard/assets/4128101/02b983a1-0c52-4fdc-94ab-8efd9f59beec)
Update copy on step 2 of staking modal to add link to each app docs

**Comment by piotr-roslaniec** [comment]
What is the address of the Random Beacon docs we should use? This is the only reference I could find on Gitbook docs: https://docs.threshold.network/app-development/random-beacon
