### ISSUE TITLE
When de-authing, fix image and cooldown period

### ISSUE THREAD

**Issue by theref** [threshold-network/token-dashboard#679]
![image](https://github.com/threshold-network/token-dashboard/assets/4128101/d51b581a-a61c-448b-92e9-d85b1746943f)

**Comment by derekpierre** [comment]
Does this issue envision anything more involved than a simple modification to image like the following.

![TACoDecrease](https://github.com/threshold-network/token-dashboard/assets/19150641/b00005e2-9d03-4805-be93-0dd0bc37b53a)

Of course it can change in the medium term, but in the shorter term, is this sufficient?

cc @arjunhassard , @theref , @cygnusv

**Comment by derekpierre** [comment]
Image fixed via #686 , not cooldown period text.

**Comment by derekpierre** [comment]
What is the expected cool-down period for TACo - is it fixed at 6-months or does it vary based on lock-up period? Is de-auth prevented before the appropriate time has passed before the cool down can be initiated?

@cygnusv , @vzotova , @arjunhassard , @theref

**Comment by derekpierre** [comment]
So are we good with just putting 6 months then as the cool down period.

If we want to provide more context, perhaps that can be addressed in the docs somewhere? There is this section currently - https://docs.threshold.network/staking-and-running-a-node/pre-node-setup/duties-and-compensation#deauthorization-delay - though pretty straightforward anyway.
