### ISSUE TITLE
New modal for bonus related information

### ISSUE THREAD

**Issue by theref** [threshold-network/token-dashboard#680]
A separate dedicated modal  for the bonus should be presented to stakers when they attempt to authorize stake to TACo or top-up, or increase authorization

```
You have the option of locking up your tokens for longer durations in order to receive a yield bonus of corresponding size. There are 4 choices:
Note that these durations include the obligatory and universal 6 month deauthorization delay. 

Lock-up Duration | Yield Bonus 

( ) 9 months | 0.5% 
( ) 12 months | 1%
( ) 18 months | 2% 
( ) 24 months | 3% 

Amount to authorize and lock for a longer duration: [       ]
Earliest unlock date: [        ]
Bonus sum (approx): [        ]

Note that once you choose a lock-up duration and hit Authorize below, your tokens will be irreversibly locked until the unlock date at the earliest. This cannot be undone. You may authorize more tokens to the same unlock horizon before the bonus deadline (12/30/23) , but you cannot decrease the amount. You must also manually initiate deauthorization 6 months before the unlock date stated if you wish to withdraw tokens on said date. For more rules and information, head to [link to documentation]. 

I acknowledge that once I authorize, my tokens will not be withdrawable until the unlock date stated [   ] 

[Go back] [Authorize] 
```

![image](https://github.com/threshold-network/token-dashboard/assets/4128101/1cd7a9a2-98f8-498f-ad84-acb576c49cb8)

Besides this totally new modal for first-time authorization, we also need distinct warnings & acknowledgement for the following post-authorization scenarios 
i) Before deadline top-up
ii) After deadline top-up
iii) Deauthorization (before & after deadline can be the same, I think)

**Comment by piotr-roslaniec** [comment]
@theref Could you also add the references to the relevant smart contract calls if you have them on hand?

**Comment by theref** [comment]
> @theref Could you also add the references to the relevant smart contract calls if you have them on hand?

https://github.com/nucypher/nucypher-contracts/blob/5815446b7b8c307ab2bd5b066a9192815648653b/contracts/contracts/TACoApplication.sol#L604

**Comment by theref** [comment]
> @theref Could you also add the references to the relevant smart contract calls if you have them on hand?

I've just realised that you may have meant in the app itself? do you think there should be a link to etherscan or something?

**Comment by piotr-roslaniec** [comment]
@theref No no, we're good - I meant the references to contract sources
