### ISSUE TITLE
Add a notification in the dashboard for fee holiday

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#695]
In the dashboard, display a note for the fee holiday (could be an info bar on top or a modal or a callout in the mint container) indicating our fee holiday. Suggestged text (with a holiday spirited festive image if there is space) 

"Ho ho ho! No bridge fees until February 10, 2024!"
```[tasklist]
### Pull Requests
- [ ] https://github.com/threshold-network/token-dashboard/pull/702
- [ ] https://github.com/threshold-network/token-dashboard/pull/711
```

**Comment by SorinQ** [comment]
Hi @michalsmiarowski Please find the design of the banner here:
https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Tasks?type=design&node-id=3865-803&mode=design&t=AqhvhadPd2C1JdlB-4

Sample:
<img width="1040" alt="Final" src="https://github.com/threshold-network/token-dashboard/assets/37292909/17d552ea-d1d3-4cbb-ac3c-aaa70e37f375">
