### ISSUE TITLE
Implement TRM wallet screening integration

### ISSUE THREAD

**Issue by evandrosaturnino** [threshold-network/token-dashboard#740]
TRM Labs has a wallet screening service that detects if a wallet address has been sanctioned by one or more key regulatory bodies. The scope of this issue comprehends in implementing the TRM wallet screening API functionality into the app to block specific users from interacting with contract functions based on their risk score metrics returned by the TRM API.

The scope of this issue consists of the following tasks:

- [X] - Implement the logic structure for retrieving wallet screening data from the TRM API. This process should use the POST method to fetch data. It is necessary to transmit the wallet address and chainID to the TRM API's wallet screening endpoint to obtain the risk score and any associated risk indicators.
- [X] - Depending on the risk score received from the TRM API endpoint, a mechanism should be established to prevent the wallet address from interacting with contract functions in the UI. Therefore, appropriate validation must be integrated to enforce this restriction based on the wallet's risk score.
- [X] - The wallet address that the user connects to the app should be submitted to TRM Labs for risk assessment. It must undergo TRM's validation and data processing. Based on the resulting score, the system should determine whether to allow or block the user from performing any contract interactions in the UI.

**Comment by michalsmiarowski** [comment]
Implemented in #736 and #761.

Closing the issue
