### ISSUE TITLE
Stake amount incorrect for a migrated legacy stake

### ISSUE THREAD

**Issue by cygnusv** [threshold-network/token-dashboard#96]
We tested migration of a legacy NU stake on mainnet and we noticed that in the Threshold dashboard it reports a stake of 0 T. The account of the stake owner is `0xd0908b1e0f6e64e3097c663bf95e2e9c040dd40d`; it's also the same address for the staking provider.

I suspect that the dashboard is not correctly adding up all the T components of the stake. Recall that a T stake is composed of three parts: native T, T from a legacy KEEP stake, T from a legacy NU stake. These are retrieved from the `stakes()` function on `TokenStaking.sol` and returned as a 3-tuple:
```js

    /// @notice Returns staked amount of T, Keep and Nu for the specified
    ///         staking provider.
    /// @dev    All values are in T denomination
    function stakes(address stakingProvider)
        external
        view
        override
        returns (
            uint96 tStake,
            uint96 keepInTStake,
            uint96 nuInTStake
        )
 ```

For example, for the `0xd0908b1e0f6e64e3097c663bf95e2e9c040dd40d` staking provider, you'll get the following values:
```
tStake: "0"
keepInTStake: "0"
nuInTStake: "566486463971216779444545"
```

**Comment by vepkenez** [comment]
Also this may be related:  https://discord.com/channels/866378471868727316/870383405936820224/959932357564063815
