### ISSUE TITLE
Don't try to upgrade amounts below the conversion precision

### ISSUE THREAD

**Issue by cygnusv** [threshold-network/token-dashboard#98]
There's a recurring problem with Vending Machine users when they upgrade amounts with too many decimals. Vending machines have a hard-coded precision of 3 decimal places, and below that precision any passed amount is ignored for conversion purposes. The problem is that this leaves some "dust" tokens authorized to the vending machine contract, and this makes upgrade calls to fail later since some ERC20 implementations check for this (at least NuCypher token, see also the ERC20 reference to this respect https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#approve).

The solution is very simple: don't pass amounts to convert below the third decimal position.
E.g., if the user has `1234.56789 NU` tokens, the UI will only show `1234.567 NU` and use `1234567000000000000000` as input amount to the vending machine, regardless if there's still `0.00089 NU` in the user address.

**Comment by r-czajkowski** [comment]
Fixed in #99.
